sudo: required

branches:
  only:
  - travis-ci

language: minimal

cache:
  directories:
  - $TRAVIS_BUILD_DIR/dl
  - $HOME/.buildroot-ccache

services:
  - docker

before_install:
- docker pull batocera/batocera.linux-build
- docker run -d batocera/batocera.linux-build /bin/bash -c "echo $(pwd)"
- docker ps -a
