sudo: required

branches:
  only:
  - travis-ci

language: minimal

cache:
  directories:
  - $HOME/dl
  - $HOME/.buildroot-ccache

services:
  - docker

before_install:
- docker pull batocera/batocera.linux-build
- docker run -d batocera/batocera.linux-build -v $TRAVIS_BUILD_DIR:/build -v $HOME/dl:/build/dl
