sudo: required

branches:
  only:
  - travis-ci

language: minimal

cache:
  directories:
  - $HOME/dl
  - $HOME/.buildroot-ccache

services:
  - docker

before_install:
  - docker pull batocera/batocera.linux-build
  - mkdir $HOME/x86_64

script:
  - docker run -d -v $TRAVIS_BUILD_DIR:/build -v $HOME/dl:/build/dl -v $HOME/x86_64:/x86_64 batocera/batocera.linux-build /bin/bash -c "cd /x86_64; make -O=/build  batocera-x86_64_defconfig; time make | tee make.log"
